
<div class="col-sm-6 col-md-12 col-toc hide">
    <div class="panel panel-default">
        <div class="panel-heading">TOC</div>
        <div class="panel-body">

        </div>
    </div>
</div>

<div class="col-sm-6 col-md-12 hide">
    <div class="panel panel-default">
        <div class="panel-heading">Site</div>
        <div class="panel-body">
            <ul>
                $header_nav_links()$
            </ul>
        </div>
    </div>
</div>



<div class="col-sm-6 col-md-12 hide">
    <div class="panel panel-default">
        <div class="panel-heading">Userbox</div>
        <div class="panel-body">
            <ul>
                <li><a class="registerlink hide" href="$base$/_register">Create account</a></li>
                <li><a class="loginlink" href="$base$/_login">Login</a></li>
                <li><a class="logoutlink" href="$base$/_logout">Logout <span class="logged_in_user"></span></a></li>
            </ul>
        </div>
    </div>
</div>
